name: flutter_notif_getx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.3.8
  get_storage: ^2.0.3
  flutter_local_notifications: ^9.0.0
  # alarm_manager: ^0.4.0
  # android_alarm_manager_plus: ^3.0.4
  intl: ^0.17.0
  timezone: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
